package com.oriental.manage.pojo.institution;

import com.oriental.manage.pojo.base.BaseModel;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * Created by wangjun on 2016/6/24.
 * 业务资金源支付机构银行强绑关系
 */
public class BusitypeOrgRelationship extends BaseModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.BUSI_TYPE
     *
     * @mbggenerated
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    private String payOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.BANK_TYPE
     *
     * @mbggenerated
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.BANK_CODE
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.ENABLE_FLAG
     *
     * @mbggenerated
     */
    private String enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.CREATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyyMMdd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busitype_org_relationship.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyyMMdd")
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.ID
     *
     * @return the value of t_busitype_org_relationship.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.ID
     *
     * @param id the value for t_busitype_org_relationship.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.BUSI_TYPE
     *
     * @return the value of t_busitype_org_relationship.BUSI_TYPE
     *
     * @mbggenerated
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.BUSI_TYPE
     *
     * @param busiType the value for t_busitype_org_relationship.BUSI_TYPE
     *
     * @mbggenerated
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.PAY_ORG_CODE
     *
     * @return the value of t_busitype_org_relationship.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    public String getPayOrgCode() {
        return payOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.PAY_ORG_CODE
     *
     * @param payOrgCode the value for t_busitype_org_relationship.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    public void setPayOrgCode(String payOrgCode) {
        this.payOrgCode = payOrgCode == null ? null : payOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.BANK_TYPE
     *
     * @return the value of t_busitype_org_relationship.BANK_TYPE
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.BANK_TYPE
     *
     * @param bankType the value for t_busitype_org_relationship.BANK_TYPE
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.BANK_CODE
     *
     * @return the value of t_busitype_org_relationship.BANK_CODE
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.BANK_CODE
     *
     * @param bankCode the value for t_busitype_org_relationship.BANK_CODE
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.ENABLE_FLAG
     *
     * @return the value of t_busitype_org_relationship.ENABLE_FLAG
     *
     * @mbggenerated
     */
    public String getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.ENABLE_FLAG
     *
     * @param enableFlag the value for t_busitype_org_relationship.ENABLE_FLAG
     *
     * @mbggenerated
     */
    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag == null ? null : enableFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.CREATE_TIME
     *
     * @return the value of t_busitype_org_relationship.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.CREATE_TIME
     *
     * @param createTime the value for t_busitype_org_relationship.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busitype_org_relationship.LAST_UPD_TIME
     *
     * @return the value of t_busitype_org_relationship.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busitype_org_relationship.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_busitype_org_relationship.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}
