package com.oriental.manage.pojo.institution;

import com.oriental.manage.pojo.base.BaseModel;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class OrgCertificateInfo extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.ORG_CODE
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.LOCAL_FILENAME
     *
     * @mbggenerated
     */
    private String localFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.DFS_FULL_FILENAME
     *
     * @mbggenerated
     */
    private String dfsFullFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.OPERATE_STATUS
     *
     * @mbggenerated
     */
    private String operateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.OPERATOR_APPLY_OPEN
     *
     * @mbggenerated
     */
    private String operatorApplyOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.OPERATOR_CONFIRM_OPEN
     *
     * @mbggenerated
     */
    private String operatorConfirmOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.OPERATOR_APPLY_CLOSE
     *
     * @mbggenerated
     */
    private String operatorApplyClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.OPERATOR_CONFIRM_CLOSE
     *
     * @mbggenerated
     */
    private String operatorConfirmClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.CERTIFICATE_TYPE
     *
     * @mbggenerated
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.EFFECT_DATA
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date effectData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.EXPIRY_DATA
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date expiryData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.CREATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_certificate_info.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.ID
     *
     * @return the value of t_org_certificate_info.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.ID
     *
     * @param id the value for t_org_certificate_info.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.ORG_CODE
     *
     * @return the value of t_org_certificate_info.ORG_CODE
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.ORG_CODE
     *
     * @param orgCode the value for t_org_certificate_info.ORG_CODE
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.LOCAL_FILENAME
     *
     * @return the value of t_org_certificate_info.LOCAL_FILENAME
     *
     * @mbggenerated
     */
    public String getLocalFilename() {
        return localFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.LOCAL_FILENAME
     *
     * @param localFilename the value for t_org_certificate_info.LOCAL_FILENAME
     *
     * @mbggenerated
     */
    public void setLocalFilename(String localFilename) {
        this.localFilename = localFilename == null ? null : localFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.DFS_FULL_FILENAME
     *
     * @return the value of t_org_certificate_info.DFS_FULL_FILENAME
     *
     * @mbggenerated
     */
    public String getDfsFullFilename() {
        return dfsFullFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.DFS_FULL_FILENAME
     *
     * @param dfsFullFilename the value for t_org_certificate_info.DFS_FULL_FILENAME
     *
     * @mbggenerated
     */
    public void setDfsFullFilename(String dfsFullFilename) {
        this.dfsFullFilename = dfsFullFilename == null ? null : dfsFullFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.STATUS
     *
     * @return the value of t_org_certificate_info.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.STATUS
     *
     * @param status the value for t_org_certificate_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.OPERATE_STATUS
     *
     * @return the value of t_org_certificate_info.OPERATE_STATUS
     *
     * @mbggenerated
     */
    public String getOperateStatus() {
        return operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.OPERATE_STATUS
     *
     * @param operateStatus the value for t_org_certificate_info.OPERATE_STATUS
     *
     * @mbggenerated
     */
    public void setOperateStatus(String operateStatus) {
        this.operateStatus = operateStatus == null ? null : operateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.OPERATOR
     *
     * @return the value of t_org_certificate_info.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.OPERATOR
     *
     * @param operator the value for t_org_certificate_info.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.OPERATOR_APPLY_OPEN
     *
     * @return the value of t_org_certificate_info.OPERATOR_APPLY_OPEN
     *
     * @mbggenerated
     */
    public String getOperatorApplyOpen() {
        return operatorApplyOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.OPERATOR_APPLY_OPEN
     *
     * @param operatorApplyOpen the value for t_org_certificate_info.OPERATOR_APPLY_OPEN
     *
     * @mbggenerated
     */
    public void setOperatorApplyOpen(String operatorApplyOpen) {
        this.operatorApplyOpen = operatorApplyOpen == null ? null : operatorApplyOpen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.OPERATOR_CONFIRM_OPEN
     *
     * @return the value of t_org_certificate_info.OPERATOR_CONFIRM_OPEN
     *
     * @mbggenerated
     */
    public String getOperatorConfirmOpen() {
        return operatorConfirmOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.OPERATOR_CONFIRM_OPEN
     *
     * @param operatorConfirmOpen the value for t_org_certificate_info.OPERATOR_CONFIRM_OPEN
     *
     * @mbggenerated
     */
    public void setOperatorConfirmOpen(String operatorConfirmOpen) {
        this.operatorConfirmOpen = operatorConfirmOpen == null ? null : operatorConfirmOpen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.OPERATOR_APPLY_CLOSE
     *
     * @return the value of t_org_certificate_info.OPERATOR_APPLY_CLOSE
     *
     * @mbggenerated
     */
    public String getOperatorApplyClose() {
        return operatorApplyClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.OPERATOR_APPLY_CLOSE
     *
     * @param operatorApplyClose the value for t_org_certificate_info.OPERATOR_APPLY_CLOSE
     *
     * @mbggenerated
     */
    public void setOperatorApplyClose(String operatorApplyClose) {
        this.operatorApplyClose = operatorApplyClose == null ? null : operatorApplyClose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.OPERATOR_CONFIRM_CLOSE
     *
     * @return the value of t_org_certificate_info.OPERATOR_CONFIRM_CLOSE
     *
     * @mbggenerated
     */
    public String getOperatorConfirmClose() {
        return operatorConfirmClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.OPERATOR_CONFIRM_CLOSE
     *
     * @param operatorConfirmClose the value for t_org_certificate_info.OPERATOR_CONFIRM_CLOSE
     *
     * @mbggenerated
     */
    public void setOperatorConfirmClose(String operatorConfirmClose) {
        this.operatorConfirmClose = operatorConfirmClose == null ? null : operatorConfirmClose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.CERTIFICATE_TYPE
     *
     * @return the value of t_org_certificate_info.CERTIFICATE_TYPE
     *
     * @mbggenerated
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.CERTIFICATE_TYPE
     *
     * @param certificateType the value for t_org_certificate_info.CERTIFICATE_TYPE
     *
     * @mbggenerated
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType == null ? null : certificateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.REMARK
     *
     * @return the value of t_org_certificate_info.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.REMARK
     *
     * @param remark the value for t_org_certificate_info.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.EFFECT_DATA
     *
     * @return the value of t_org_certificate_info.EFFECT_DATA
     *
     * @mbggenerated
     */
    public Date getEffectData() {
        return effectData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.EFFECT_DATA
     *
     * @param effectData the value for t_org_certificate_info.EFFECT_DATA
     *
     * @mbggenerated
     */
    public void setEffectData(Date effectData) {
        this.effectData = effectData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.EXPIRY_DATA
     *
     * @return the value of t_org_certificate_info.EXPIRY_DATA
     *
     * @mbggenerated
     */
    public Date getExpiryData() {
        return expiryData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.EXPIRY_DATA
     *
     * @param expiryData the value for t_org_certificate_info.EXPIRY_DATA
     *
     * @mbggenerated
     */
    public void setExpiryData(Date expiryData) {
        this.expiryData = expiryData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.CREATE_TIME
     *
     * @return the value of t_org_certificate_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.CREATE_TIME
     *
     * @param createTime the value for t_org_certificate_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.LAST_UPD_TIME
     *
     * @return the value of t_org_certificate_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_org_certificate_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_certificate_info.VERSION
     *
     * @return the value of t_org_certificate_info.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_certificate_info.VERSION
     *
     * @param version the value for t_org_certificate_info.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}