package com.oriental.manage.dao.institution;

import com.oriental.manage.pojo.institution.OrgCertificateInfo;

import java.util.List;

public interface OrgCertificateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org_certificate_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org_certificate_info
     *
     * @mbggenerated
     */
    int insert(OrgCertificateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org_certificate_info
     *
     * @mbggenerated
     */
    int insertSelective(OrgCertificateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org_certificate_info
     *
     * @mbggenerated
     */
    OrgCertificateInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org_certificate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrgCertificateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org_certificate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrgCertificateInfo record);

    List<OrgCertificateInfo> queryPage(OrgCertificateInfo orgCertificateInfo);

    List<OrgCertificateInfo> check(OrgCertificateInfo orgCertificateInfo );
}