package com.oriental.manage.dao.base;

import com.oriental.manage.pojo.base.AuthCfg;

import java.util.List;

public interface AuthCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_cfg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_cfg
     *
     * @mbggenerated
     */
    int insert(AuthCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_cfg
     *
     * @mbggenerated
     */
    int insertSelective(AuthCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_cfg
     *
     * @mbggenerated
     */
    AuthCfg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_cfg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuthCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_cfg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuthCfg record);

    void deleteByRoleId(String roleId);

    List<AuthCfg> checkAuth(String roleID);

    int deleteByPrimaryRole(String roleID);
}