package com.oriental.manage.dao.base;

import com.oriental.manage.pojo.base.DataDict;

import java.util.List;

public interface DataDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dict
     *
     * @mbggenerated
     */
    int insert(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dict
     *
     * @mbggenerated
     */
    int insertSelective(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dict
     *
     * @mbggenerated
     */
    DataDict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataDict record);

    List<DataDict> selectBySelective(DataDict dataDict);

    List<DataDict> selectByPay(DataDict dataDict);

    List<DataDict> getPage(DataDict dataDict);

    int checkDataDict(DataDict dataDict);

    List<DataDict> selectReportTypeByItemType(DataDict dataDict);
}