package com.oriental.manage.dao.base;

import com.oriental.manage.core.paging.Pagination;
import com.oriental.manage.pojo.base.OperateRecord;

import java.util.List;

public interface OperateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operate_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operate_record
     *
     * @mbggenerated
     */
    int insert(OperateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operate_record
     *
     * @mbggenerated
     */
    int insertSelective(OperateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operate_record
     *
     * @mbggenerated
     */
    OperateRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operate_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operate_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperateRecord record);

    List<OperateRecord> selectByOperateRecord(OperateRecord record);
}