package com.oriental.manage.dao.base;

import com.oriental.manage.pojo.base.RoleInfo;

import java.util.List;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbggenerated
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbggenerated
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbggenerated
     */
    RoleInfo selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleInfo record);

    List<RoleInfo> getRolesByUserId(String userId);

    List<RoleInfo> selectBySelective(RoleInfo roleInfo);

    List<RoleInfo> queryPage(RoleInfo roleInfo);

    List<RoleInfo> selectByType(RoleInfo roleInfo);
}