package com.oriental.manage.dao.refund;

import com.oriental.manage.pojo.refund.BusiRefundDetail;
import com.oriental.manage.pojo.transaction.TBusiTransDetail;

import java.util.List;
import java.util.Map;

public interface BusiRefundDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_refund_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_refund_detail
     *
     * @mbggenerated
     */
    int insert(BusiRefundDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_refund_detail
     *
     * @mbggenerated
     */
    int insertSelective(BusiRefundDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_refund_detail
     *
     * @mbggenerated
     */
    BusiRefundDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_refund_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusiRefundDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_refund_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusiRefundDetail record);

    List<TBusiTransDetail> selectForRefundApply(TBusiTransDetail tBusiTransDetail);

    Map sumFindCommonRefundOrder(TBusiTransDetail tBusiTransDetail);

    List<BusiRefundDetail> selectBySelective(BusiRefundDetail busiRefundDetail);

    Map sumBusiRefund(BusiRefundDetail busiRefundDetail);
}