package com.oriental.manage.dao.transaction;

import com.oriental.manage.pojo.transaction.TBusiTransDetail;
import com.oriental.manage.pojo.transaction.TBusiTransDetailKey;

public interface BusiTransDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_trans_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TBusiTransDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_trans_detail
     *
     * @mbggenerated
     */
    int insert(TBusiTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_trans_detail
     *
     * @mbggenerated
     */
    int insertSelective(TBusiTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_trans_detail
     *
     * @mbggenerated
     */
    TBusiTransDetail selectByPrimaryKey(TBusiTransDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_trans_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBusiTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_busi_trans_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBusiTransDetail record);
}