package com.oriental.manage.dao.transaction;

import com.oriental.manage.pojo.transaction.TPayTransDetail;
import com.oriental.manage.pojo.transaction.TPayTransDetailKey;

public interface PayTransDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_trans_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TPayTransDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_trans_detail
     *
     * @mbggenerated
     */
    int insert(TPayTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_trans_detail
     *
     * @mbggenerated
     */
    int insertSelective(TPayTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_trans_detail
     *
     * @mbggenerated
     */
    TPayTransDetail selectByPrimaryKey(TPayTransDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_trans_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TPayTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_trans_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TPayTransDetail record);
}