package com.oriental.manage.dao.transaction;

import com.oriental.manage.pojo.transaction.TOrderMain;
import com.oriental.manage.pojo.transaction.TOrderMainKey;

public interface TOrderMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_main
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TOrderMainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_main
     *
     * @mbggenerated
     */
    int insert(TOrderMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_main
     *
     * @mbggenerated
     */
    int insertSelective(TOrderMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_main
     *
     * @mbggenerated
     */
    TOrderMain selectByPrimaryKey(TOrderMainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrderMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrderMain record);
}