package com.oriental.manage.pojo.refund;

import com.oriental.manage.pojo.base.BaseModel;
import lombok.Data;

import java.util.Date;

@Data
public class BusiRefundDetail extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.MCHNT_CODE
     *
     * @mbggenerated
     */
    private String mchntCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.TOTAL_AMT
     *
     * @mbggenerated
     */
    private Long totalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.REFUND_AMT
     *
     * @mbggenerated
     */
    private Long refundAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.TOTAL_REFUND_AMOUNT
     *
     * @mbggenerated
     */
    private Long totalRefundAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    private String oldOurTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.OLD_ORDER_NO
     *
     * @mbggenerated
     */
    private String oldOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.SPLIT_INFO
     *
     * @mbggenerated
     */
    private String splitInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.ORDER_ADJ_STATUS
     *
     * @mbggenerated
     */
    private String orderAdjStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.TRANS_INFO_TYPE
     *
     * @mbggenerated
     */
    private String transInfoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.REFUND_STATUS
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.REFUND_APPLICANT
     *
     * @mbggenerated
     */
    private String refundApplicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.APPLICANT_IP
     *
     * @mbggenerated
     */
    private String applicantIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.REFUND_DATE
     *
     * @mbggenerated
     */
    private Date refundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.AUDITOR
     *
     * @mbggenerated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.AUDIT_DATE
     *
     * @mbggenerated
     */
    private Date auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.PROC_EMP_ID
     *
     * @mbggenerated
     */
    private String procEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.PROC_DATETIME
     *
     * @mbggenerated
     */
    private Date procDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.SPARE1
     *
     * @mbggenerated
     */
    private String spare1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_busi_refund_detail.SPARE2
     *
     * @mbggenerated
     */
    private String spare2;


    private Date beginDate;
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.ID
     *
     * @return the value of t_busi_refund_detail.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.ID
     *
     * @param id the value for t_busi_refund_detail.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.MCHNT_CODE
     *
     * @return the value of t_busi_refund_detail.MCHNT_CODE
     *
     * @mbggenerated
     */
    public String getMchntCode() {
        return mchntCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.MCHNT_CODE
     *
     * @param mchntCode the value for t_busi_refund_detail.MCHNT_CODE
     *
     * @mbggenerated
     */
    public void setMchntCode(String mchntCode) {
        this.mchntCode = mchntCode == null ? null : mchntCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.ORDER_NO
     *
     * @return the value of t_busi_refund_detail.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.ORDER_NO
     *
     * @param orderNo the value for t_busi_refund_detail.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.ORDER_DATE
     *
     * @return the value of t_busi_refund_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.ORDER_DATE
     *
     * @param orderDate the value for t_busi_refund_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.TOTAL_AMT
     *
     * @return the value of t_busi_refund_detail.TOTAL_AMT
     *
     * @mbggenerated
     */
    public Long getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.TOTAL_AMT
     *
     * @param totalAmt the value for t_busi_refund_detail.TOTAL_AMT
     *
     * @mbggenerated
     */
    public void setTotalAmt(Long totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.REFUND_AMT
     *
     * @return the value of t_busi_refund_detail.REFUND_AMT
     *
     * @mbggenerated
     */
    public Long getRefundAmt() {
        return refundAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.REFUND_AMT
     *
     * @param refundAmt the value for t_busi_refund_detail.REFUND_AMT
     *
     * @mbggenerated
     */
    public void setRefundAmt(Long refundAmt) {
        this.refundAmt = refundAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.TOTAL_REFUND_AMOUNT
     *
     * @return the value of t_busi_refund_detail.TOTAL_REFUND_AMOUNT
     *
     * @mbggenerated
     */
    public Long getTotalRefundAmount() {
        return totalRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.TOTAL_REFUND_AMOUNT
     *
     * @param totalRefundAmount the value for t_busi_refund_detail.TOTAL_REFUND_AMOUNT
     *
     * @mbggenerated
     */
    public void setTotalRefundAmount(Long totalRefundAmount) {
        this.totalRefundAmount = totalRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.OLD_OUR_TRANS_NO
     *
     * @return the value of t_busi_refund_detail.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOldOurTransNo() {
        return oldOurTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.OLD_OUR_TRANS_NO
     *
     * @param oldOurTransNo the value for t_busi_refund_detail.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOldOurTransNo(String oldOurTransNo) {
        this.oldOurTransNo = oldOurTransNo == null ? null : oldOurTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.OLD_ORDER_NO
     *
     * @return the value of t_busi_refund_detail.OLD_ORDER_NO
     *
     * @mbggenerated
     */
    public String getOldOrderNo() {
        return oldOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.OLD_ORDER_NO
     *
     * @param oldOrderNo the value for t_busi_refund_detail.OLD_ORDER_NO
     *
     * @mbggenerated
     */
    public void setOldOrderNo(String oldOrderNo) {
        this.oldOrderNo = oldOrderNo == null ? null : oldOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.SPLIT_INFO
     *
     * @return the value of t_busi_refund_detail.SPLIT_INFO
     *
     * @mbggenerated
     */
    public String getSplitInfo() {
        return splitInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.SPLIT_INFO
     *
     * @param splitInfo the value for t_busi_refund_detail.SPLIT_INFO
     *
     * @mbggenerated
     */
    public void setSplitInfo(String splitInfo) {
        this.splitInfo = splitInfo == null ? null : splitInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.ORDER_ADJ_STATUS
     *
     * @return the value of t_busi_refund_detail.ORDER_ADJ_STATUS
     *
     * @mbggenerated
     */
    public String getOrderAdjStatus() {
        return orderAdjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.ORDER_ADJ_STATUS
     *
     * @param orderAdjStatus the value for t_busi_refund_detail.ORDER_ADJ_STATUS
     *
     * @mbggenerated
     */
    public void setOrderAdjStatus(String orderAdjStatus) {
        this.orderAdjStatus = orderAdjStatus == null ? null : orderAdjStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.TRANS_INFO_TYPE
     *
     * @return the value of t_busi_refund_detail.TRANS_INFO_TYPE
     *
     * @mbggenerated
     */
    public String getTransInfoType() {
        return transInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.TRANS_INFO_TYPE
     *
     * @param transInfoType the value for t_busi_refund_detail.TRANS_INFO_TYPE
     *
     * @mbggenerated
     */
    public void setTransInfoType(String transInfoType) {
        this.transInfoType = transInfoType == null ? null : transInfoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.REFUND_STATUS
     *
     * @return the value of t_busi_refund_detail.REFUND_STATUS
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.REFUND_STATUS
     *
     * @param refundStatus the value for t_busi_refund_detail.REFUND_STATUS
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.REFUND_APPLICANT
     *
     * @return the value of t_busi_refund_detail.REFUND_APPLICANT
     *
     * @mbggenerated
     */
    public String getRefundApplicant() {
        return refundApplicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.REFUND_APPLICANT
     *
     * @param refundApplicant the value for t_busi_refund_detail.REFUND_APPLICANT
     *
     * @mbggenerated
     */
    public void setRefundApplicant(String refundApplicant) {
        this.refundApplicant = refundApplicant == null ? null : refundApplicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.APPLICANT_IP
     *
     * @return the value of t_busi_refund_detail.APPLICANT_IP
     *
     * @mbggenerated
     */
    public String getApplicantIp() {
        return applicantIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.APPLICANT_IP
     *
     * @param applicantIp the value for t_busi_refund_detail.APPLICANT_IP
     *
     * @mbggenerated
     */
    public void setApplicantIp(String applicantIp) {
        this.applicantIp = applicantIp == null ? null : applicantIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.REFUND_DATE
     *
     * @return the value of t_busi_refund_detail.REFUND_DATE
     *
     * @mbggenerated
     */
    public Date getRefundDate() {
        return refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.REFUND_DATE
     *
     * @param refundDate the value for t_busi_refund_detail.REFUND_DATE
     *
     * @mbggenerated
     */
    public void setRefundDate(Date refundDate) {
        this.refundDate = refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.AUDITOR
     *
     * @return the value of t_busi_refund_detail.AUDITOR
     *
     * @mbggenerated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.AUDITOR
     *
     * @param auditor the value for t_busi_refund_detail.AUDITOR
     *
     * @mbggenerated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.AUDIT_DATE
     *
     * @return the value of t_busi_refund_detail.AUDIT_DATE
     *
     * @mbggenerated
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.AUDIT_DATE
     *
     * @param auditDate the value for t_busi_refund_detail.AUDIT_DATE
     *
     * @mbggenerated
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.PROC_EMP_ID
     *
     * @return the value of t_busi_refund_detail.PROC_EMP_ID
     *
     * @mbggenerated
     */
    public String getProcEmpId() {
        return procEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.PROC_EMP_ID
     *
     * @param procEmpId the value for t_busi_refund_detail.PROC_EMP_ID
     *
     * @mbggenerated
     */
    public void setProcEmpId(String procEmpId) {
        this.procEmpId = procEmpId == null ? null : procEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.PROC_DATETIME
     *
     * @return the value of t_busi_refund_detail.PROC_DATETIME
     *
     * @mbggenerated
     */
    public Date getProcDatetime() {
        return procDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.PROC_DATETIME
     *
     * @param procDatetime the value for t_busi_refund_detail.PROC_DATETIME
     *
     * @mbggenerated
     */
    public void setProcDatetime(Date procDatetime) {
        this.procDatetime = procDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.CREATE_TIME
     *
     * @return the value of t_busi_refund_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.CREATE_TIME
     *
     * @param createTime the value for t_busi_refund_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.LAST_UPD_TIME
     *
     * @return the value of t_busi_refund_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_busi_refund_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.SPARE1
     *
     * @return the value of t_busi_refund_detail.SPARE1
     *
     * @mbggenerated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.SPARE1
     *
     * @param spare1 the value for t_busi_refund_detail.SPARE1
     *
     * @mbggenerated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_busi_refund_detail.SPARE2
     *
     * @return the value of t_busi_refund_detail.SPARE2
     *
     * @mbggenerated
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_busi_refund_detail.SPARE2
     *
     * @param spare2 the value for t_busi_refund_detail.SPARE2
     *
     * @mbggenerated
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }
}