package com.oriental.manage.pojo.refund;

import java.util.Date;

public class OrgRefundDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    private String payOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.ORG_BANK_CODE
     *
     * @mbggenerated
     */
    private String orgBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.REFUND_AMT
     *
     * @mbggenerated
     */
    private Long refundAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.TOTAL_AMT
     *
     * @mbggenerated
     */
    private Long totalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.BUSI_REFUND_ID
     *
     * @mbggenerated
     */
    private String busiRefundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.PAY_TRANS_NO
     *
     * @mbggenerated
     */
    private String payTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.OLD_PAY_TRANS_NO
     *
     * @mbggenerated
     */
    private String oldPayTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    private String oldOurTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.OLD_PAY_REQ_NO
     *
     * @mbggenerated
     */
    private String oldPayReqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.ORDER_ADJ_STATUS
     *
     * @mbggenerated
     */
    private String orderAdjStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.REFUND_TYPE
     *
     * @mbggenerated
     */
    private String refundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.ERR_TYPE
     *
     * @mbggenerated
     */
    private String errType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.TRANS_INFO_TYPE
     *
     * @mbggenerated
     */
    private String transInfoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.REFUND_STATUS
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.REFUND_APPLICANT
     *
     * @mbggenerated
     */
    private String refundApplicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.APPLICANT_IP
     *
     * @mbggenerated
     */
    private String applicantIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.AUDITOR
     *
     * @mbggenerated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.AUDIT_DATE
     *
     * @mbggenerated
     */
    private Date auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.PROC_EMP_ID
     *
     * @mbggenerated
     */
    private String procEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.PROC_DATETIME
     *
     * @mbggenerated
     */
    private Date procDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.SPARE1
     *
     * @mbggenerated
     */
    private String spare1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org_refund_detail.SPARE2
     *
     * @mbggenerated
     */
    private String spare2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.ID
     *
     * @return the value of t_org_refund_detail.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.ID
     *
     * @param id the value for t_org_refund_detail.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.ORDER_NO
     *
     * @return the value of t_org_refund_detail.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.ORDER_NO
     *
     * @param orderNo the value for t_org_refund_detail.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.ORDER_DATE
     *
     * @return the value of t_org_refund_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.ORDER_DATE
     *
     * @param orderDate the value for t_org_refund_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.CHANNEL
     *
     * @return the value of t_org_refund_detail.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.CHANNEL
     *
     * @param channel the value for t_org_refund_detail.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.PAY_ORG_CODE
     *
     * @return the value of t_org_refund_detail.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    public String getPayOrgCode() {
        return payOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.PAY_ORG_CODE
     *
     * @param payOrgCode the value for t_org_refund_detail.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    public void setPayOrgCode(String payOrgCode) {
        this.payOrgCode = payOrgCode == null ? null : payOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.ORG_BANK_CODE
     *
     * @return the value of t_org_refund_detail.ORG_BANK_CODE
     *
     * @mbggenerated
     */
    public String getOrgBankCode() {
        return orgBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.ORG_BANK_CODE
     *
     * @param orgBankCode the value for t_org_refund_detail.ORG_BANK_CODE
     *
     * @mbggenerated
     */
    public void setOrgBankCode(String orgBankCode) {
        this.orgBankCode = orgBankCode == null ? null : orgBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.REFUND_AMT
     *
     * @return the value of t_org_refund_detail.REFUND_AMT
     *
     * @mbggenerated
     */
    public Long getRefundAmt() {
        return refundAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.REFUND_AMT
     *
     * @param refundAmt the value for t_org_refund_detail.REFUND_AMT
     *
     * @mbggenerated
     */
    public void setRefundAmt(Long refundAmt) {
        this.refundAmt = refundAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.TOTAL_AMT
     *
     * @return the value of t_org_refund_detail.TOTAL_AMT
     *
     * @mbggenerated
     */
    public Long getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.TOTAL_AMT
     *
     * @param totalAmt the value for t_org_refund_detail.TOTAL_AMT
     *
     * @mbggenerated
     */
    public void setTotalAmt(Long totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.BUSI_REFUND_ID
     *
     * @return the value of t_org_refund_detail.BUSI_REFUND_ID
     *
     * @mbggenerated
     */
    public String getBusiRefundId() {
        return busiRefundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.BUSI_REFUND_ID
     *
     * @param busiRefundId the value for t_org_refund_detail.BUSI_REFUND_ID
     *
     * @mbggenerated
     */
    public void setBusiRefundId(String busiRefundId) {
        this.busiRefundId = busiRefundId == null ? null : busiRefundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.PAY_TRANS_NO
     *
     * @return the value of t_org_refund_detail.PAY_TRANS_NO
     *
     * @mbggenerated
     */
    public String getPayTransNo() {
        return payTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.PAY_TRANS_NO
     *
     * @param payTransNo the value for t_org_refund_detail.PAY_TRANS_NO
     *
     * @mbggenerated
     */
    public void setPayTransNo(String payTransNo) {
        this.payTransNo = payTransNo == null ? null : payTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.OLD_PAY_TRANS_NO
     *
     * @return the value of t_org_refund_detail.OLD_PAY_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOldPayTransNo() {
        return oldPayTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.OLD_PAY_TRANS_NO
     *
     * @param oldPayTransNo the value for t_org_refund_detail.OLD_PAY_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOldPayTransNo(String oldPayTransNo) {
        this.oldPayTransNo = oldPayTransNo == null ? null : oldPayTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.OLD_OUR_TRANS_NO
     *
     * @return the value of t_org_refund_detail.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOldOurTransNo() {
        return oldOurTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.OLD_OUR_TRANS_NO
     *
     * @param oldOurTransNo the value for t_org_refund_detail.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOldOurTransNo(String oldOurTransNo) {
        this.oldOurTransNo = oldOurTransNo == null ? null : oldOurTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.OLD_PAY_REQ_NO
     *
     * @return the value of t_org_refund_detail.OLD_PAY_REQ_NO
     *
     * @mbggenerated
     */
    public String getOldPayReqNo() {
        return oldPayReqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.OLD_PAY_REQ_NO
     *
     * @param oldPayReqNo the value for t_org_refund_detail.OLD_PAY_REQ_NO
     *
     * @mbggenerated
     */
    public void setOldPayReqNo(String oldPayReqNo) {
        this.oldPayReqNo = oldPayReqNo == null ? null : oldPayReqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.ORDER_ADJ_STATUS
     *
     * @return the value of t_org_refund_detail.ORDER_ADJ_STATUS
     *
     * @mbggenerated
     */
    public String getOrderAdjStatus() {
        return orderAdjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.ORDER_ADJ_STATUS
     *
     * @param orderAdjStatus the value for t_org_refund_detail.ORDER_ADJ_STATUS
     *
     * @mbggenerated
     */
    public void setOrderAdjStatus(String orderAdjStatus) {
        this.orderAdjStatus = orderAdjStatus == null ? null : orderAdjStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.REFUND_TYPE
     *
     * @return the value of t_org_refund_detail.REFUND_TYPE
     *
     * @mbggenerated
     */
    public String getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.REFUND_TYPE
     *
     * @param refundType the value for t_org_refund_detail.REFUND_TYPE
     *
     * @mbggenerated
     */
    public void setRefundType(String refundType) {
        this.refundType = refundType == null ? null : refundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.ERR_TYPE
     *
     * @return the value of t_org_refund_detail.ERR_TYPE
     *
     * @mbggenerated
     */
    public String getErrType() {
        return errType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.ERR_TYPE
     *
     * @param errType the value for t_org_refund_detail.ERR_TYPE
     *
     * @mbggenerated
     */
    public void setErrType(String errType) {
        this.errType = errType == null ? null : errType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.TRANS_INFO_TYPE
     *
     * @return the value of t_org_refund_detail.TRANS_INFO_TYPE
     *
     * @mbggenerated
     */
    public String getTransInfoType() {
        return transInfoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.TRANS_INFO_TYPE
     *
     * @param transInfoType the value for t_org_refund_detail.TRANS_INFO_TYPE
     *
     * @mbggenerated
     */
    public void setTransInfoType(String transInfoType) {
        this.transInfoType = transInfoType == null ? null : transInfoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.REFUND_STATUS
     *
     * @return the value of t_org_refund_detail.REFUND_STATUS
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.REFUND_STATUS
     *
     * @param refundStatus the value for t_org_refund_detail.REFUND_STATUS
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.REFUND_APPLICANT
     *
     * @return the value of t_org_refund_detail.REFUND_APPLICANT
     *
     * @mbggenerated
     */
    public String getRefundApplicant() {
        return refundApplicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.REFUND_APPLICANT
     *
     * @param refundApplicant the value for t_org_refund_detail.REFUND_APPLICANT
     *
     * @mbggenerated
     */
    public void setRefundApplicant(String refundApplicant) {
        this.refundApplicant = refundApplicant == null ? null : refundApplicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.APPLICANT_IP
     *
     * @return the value of t_org_refund_detail.APPLICANT_IP
     *
     * @mbggenerated
     */
    public String getApplicantIp() {
        return applicantIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.APPLICANT_IP
     *
     * @param applicantIp the value for t_org_refund_detail.APPLICANT_IP
     *
     * @mbggenerated
     */
    public void setApplicantIp(String applicantIp) {
        this.applicantIp = applicantIp == null ? null : applicantIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.AUDITOR
     *
     * @return the value of t_org_refund_detail.AUDITOR
     *
     * @mbggenerated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.AUDITOR
     *
     * @param auditor the value for t_org_refund_detail.AUDITOR
     *
     * @mbggenerated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.AUDIT_DATE
     *
     * @return the value of t_org_refund_detail.AUDIT_DATE
     *
     * @mbggenerated
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.AUDIT_DATE
     *
     * @param auditDate the value for t_org_refund_detail.AUDIT_DATE
     *
     * @mbggenerated
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.PROC_EMP_ID
     *
     * @return the value of t_org_refund_detail.PROC_EMP_ID
     *
     * @mbggenerated
     */
    public String getProcEmpId() {
        return procEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.PROC_EMP_ID
     *
     * @param procEmpId the value for t_org_refund_detail.PROC_EMP_ID
     *
     * @mbggenerated
     */
    public void setProcEmpId(String procEmpId) {
        this.procEmpId = procEmpId == null ? null : procEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.PROC_DATETIME
     *
     * @return the value of t_org_refund_detail.PROC_DATETIME
     *
     * @mbggenerated
     */
    public Date getProcDatetime() {
        return procDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.PROC_DATETIME
     *
     * @param procDatetime the value for t_org_refund_detail.PROC_DATETIME
     *
     * @mbggenerated
     */
    public void setProcDatetime(Date procDatetime) {
        this.procDatetime = procDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.CREATE_TIME
     *
     * @return the value of t_org_refund_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.CREATE_TIME
     *
     * @param createTime the value for t_org_refund_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.LAST_UPD_TIME
     *
     * @return the value of t_org_refund_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_org_refund_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.SPARE1
     *
     * @return the value of t_org_refund_detail.SPARE1
     *
     * @mbggenerated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.SPARE1
     *
     * @param spare1 the value for t_org_refund_detail.SPARE1
     *
     * @mbggenerated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org_refund_detail.SPARE2
     *
     * @return the value of t_org_refund_detail.SPARE2
     *
     * @mbggenerated
     */
    public String getSpare2() {
        return spare2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org_refund_detail.SPARE2
     *
     * @param spare2 the value for t_org_refund_detail.SPARE2
     *
     * @mbggenerated
     */
    public void setSpare2(String spare2) {
        this.spare2 = spare2 == null ? null : spare2.trim();
    }
}