package com.oriental.manage.pojo.transaction;

import java.util.Date;

public class TOrderMainKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.SETTLE_DATE
     *
     * @mbggenerated
     */
    private Date settleDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ID
     *
     * @return the value of t_order_main.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ID
     *
     * @param id the value for t_order_main.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.SETTLE_DATE
     *
     * @return the value of t_order_main.SETTLE_DATE
     *
     * @mbggenerated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.SETTLE_DATE
     *
     * @param settleDate the value for t_order_main.SETTLE_DATE
     *
     * @mbggenerated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }
}