package com.oriental.manage.pojo.transaction;

import java.util.Date;

public class TOrderMain extends TOrderMainKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.MCHNT_CODE
     *
     * @mbggenerated
     */
    private String mchntCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ORDER_DATE
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ORDER_TYPE
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.OUR_TRANS_NO
     *
     * @mbggenerated
     */
    private String ourTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ESCROW_NO
     *
     * @mbggenerated
     */
    private String escrowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.TOTAL_AMT
     *
     * @mbggenerated
     */
    private Long totalAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CURTYPE
     *
     * @mbggenerated
     */
    private String curtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.PG_URL
     *
     * @mbggenerated
     */
    private String pgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.BG_URL
     *
     * @mbggenerated
     */
    private String bgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CALLBACK_TYPE
     *
     * @mbggenerated
     */
    private String callbackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.NOTIFY_TYPE
     *
     * @mbggenerated
     */
    private String notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.NOTIFY_STATUS
     *
     * @mbggenerated
     */
    private String notifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.NOTIFY_DESC
     *
     * @mbggenerated
     */
    private String notifyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.GOODS_TYPE
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.GOODS_NAME
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.MCC_TYPE
     *
     * @mbggenerated
     */
    private String mccType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.MCC_NAME
     *
     * @mbggenerated
     */
    private String mccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.MAC
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ENCRYPT_TYPE
     *
     * @mbggenerated
     */
    private String encryptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CLIENT_IP
     *
     * @mbggenerated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ACCEPT_SRV_IP
     *
     * @mbggenerated
     */
    private String acceptSrvIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    private String oldOurTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.REVERSE_FLAG
     *
     * @mbggenerated
     */
    private String reverseFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.ATTACH
     *
     * @mbggenerated
     */
    private String attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CHK_STATUS
     *
     * @mbggenerated
     */
    private String chkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CHK_BATCH_NO
     *
     * @mbggenerated
     */
    private String chkBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.DELETE_FLAG
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.MCHNT_CODE
     *
     * @return the value of t_order_main.MCHNT_CODE
     *
     * @mbggenerated
     */
    public String getMchntCode() {
        return mchntCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.MCHNT_CODE
     *
     * @param mchntCode the value for t_order_main.MCHNT_CODE
     *
     * @mbggenerated
     */
    public void setMchntCode(String mchntCode) {
        this.mchntCode = mchntCode == null ? null : mchntCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ORDER_NO
     *
     * @return the value of t_order_main.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ORDER_NO
     *
     * @param orderNo the value for t_order_main.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ORDER_DATE
     *
     * @return the value of t_order_main.ORDER_DATE
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ORDER_DATE
     *
     * @param orderDate the value for t_order_main.ORDER_DATE
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ORDER_TYPE
     *
     * @return the value of t_order_main.ORDER_TYPE
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ORDER_TYPE
     *
     * @param orderType the value for t_order_main.ORDER_TYPE
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CHANNEL
     *
     * @return the value of t_order_main.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CHANNEL
     *
     * @param channel the value for t_order_main.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.OUR_TRANS_NO
     *
     * @return the value of t_order_main.OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOurTransNo() {
        return ourTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.OUR_TRANS_NO
     *
     * @param ourTransNo the value for t_order_main.OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOurTransNo(String ourTransNo) {
        this.ourTransNo = ourTransNo == null ? null : ourTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ESCROW_NO
     *
     * @return the value of t_order_main.ESCROW_NO
     *
     * @mbggenerated
     */
    public String getEscrowNo() {
        return escrowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ESCROW_NO
     *
     * @param escrowNo the value for t_order_main.ESCROW_NO
     *
     * @mbggenerated
     */
    public void setEscrowNo(String escrowNo) {
        this.escrowNo = escrowNo == null ? null : escrowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ORDER_STATUS
     *
     * @return the value of t_order_main.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ORDER_STATUS
     *
     * @param orderStatus the value for t_order_main.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.TOTAL_AMT
     *
     * @return the value of t_order_main.TOTAL_AMT
     *
     * @mbggenerated
     */
    public Long getTotalAmt() {
        return totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.TOTAL_AMT
     *
     * @param totalAmt the value for t_order_main.TOTAL_AMT
     *
     * @mbggenerated
     */
    public void setTotalAmt(Long totalAmt) {
        this.totalAmt = totalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CURTYPE
     *
     * @return the value of t_order_main.CURTYPE
     *
     * @mbggenerated
     */
    public String getCurtype() {
        return curtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CURTYPE
     *
     * @param curtype the value for t_order_main.CURTYPE
     *
     * @mbggenerated
     */
    public void setCurtype(String curtype) {
        this.curtype = curtype == null ? null : curtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.PG_URL
     *
     * @return the value of t_order_main.PG_URL
     *
     * @mbggenerated
     */
    public String getPgUrl() {
        return pgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.PG_URL
     *
     * @param pgUrl the value for t_order_main.PG_URL
     *
     * @mbggenerated
     */
    public void setPgUrl(String pgUrl) {
        this.pgUrl = pgUrl == null ? null : pgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.BG_URL
     *
     * @return the value of t_order_main.BG_URL
     *
     * @mbggenerated
     */
    public String getBgUrl() {
        return bgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.BG_URL
     *
     * @param bgUrl the value for t_order_main.BG_URL
     *
     * @mbggenerated
     */
    public void setBgUrl(String bgUrl) {
        this.bgUrl = bgUrl == null ? null : bgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CALLBACK_TYPE
     *
     * @return the value of t_order_main.CALLBACK_TYPE
     *
     * @mbggenerated
     */
    public String getCallbackType() {
        return callbackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CALLBACK_TYPE
     *
     * @param callbackType the value for t_order_main.CALLBACK_TYPE
     *
     * @mbggenerated
     */
    public void setCallbackType(String callbackType) {
        this.callbackType = callbackType == null ? null : callbackType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.NOTIFY_TYPE
     *
     * @return the value of t_order_main.NOTIFY_TYPE
     *
     * @mbggenerated
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.NOTIFY_TYPE
     *
     * @param notifyType the value for t_order_main.NOTIFY_TYPE
     *
     * @mbggenerated
     */
    public void setNotifyType(String notifyType) {
        this.notifyType = notifyType == null ? null : notifyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.NOTIFY_STATUS
     *
     * @return the value of t_order_main.NOTIFY_STATUS
     *
     * @mbggenerated
     */
    public String getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.NOTIFY_STATUS
     *
     * @param notifyStatus the value for t_order_main.NOTIFY_STATUS
     *
     * @mbggenerated
     */
    public void setNotifyStatus(String notifyStatus) {
        this.notifyStatus = notifyStatus == null ? null : notifyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.NOTIFY_DESC
     *
     * @return the value of t_order_main.NOTIFY_DESC
     *
     * @mbggenerated
     */
    public String getNotifyDesc() {
        return notifyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.NOTIFY_DESC
     *
     * @param notifyDesc the value for t_order_main.NOTIFY_DESC
     *
     * @mbggenerated
     */
    public void setNotifyDesc(String notifyDesc) {
        this.notifyDesc = notifyDesc == null ? null : notifyDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.GOODS_TYPE
     *
     * @return the value of t_order_main.GOODS_TYPE
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.GOODS_TYPE
     *
     * @param goodsType the value for t_order_main.GOODS_TYPE
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.GOODS_NAME
     *
     * @return the value of t_order_main.GOODS_NAME
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.GOODS_NAME
     *
     * @param goodsName the value for t_order_main.GOODS_NAME
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.MCC_TYPE
     *
     * @return the value of t_order_main.MCC_TYPE
     *
     * @mbggenerated
     */
    public String getMccType() {
        return mccType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.MCC_TYPE
     *
     * @param mccType the value for t_order_main.MCC_TYPE
     *
     * @mbggenerated
     */
    public void setMccType(String mccType) {
        this.mccType = mccType == null ? null : mccType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.MCC_NAME
     *
     * @return the value of t_order_main.MCC_NAME
     *
     * @mbggenerated
     */
    public String getMccName() {
        return mccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.MCC_NAME
     *
     * @param mccName the value for t_order_main.MCC_NAME
     *
     * @mbggenerated
     */
    public void setMccName(String mccName) {
        this.mccName = mccName == null ? null : mccName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.PRODUCT_ID
     *
     * @return the value of t_order_main.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.PRODUCT_ID
     *
     * @param productId the value for t_order_main.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.MAC
     *
     * @return the value of t_order_main.MAC
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.MAC
     *
     * @param mac the value for t_order_main.MAC
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ENCRYPT_TYPE
     *
     * @return the value of t_order_main.ENCRYPT_TYPE
     *
     * @mbggenerated
     */
    public String getEncryptType() {
        return encryptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ENCRYPT_TYPE
     *
     * @param encryptType the value for t_order_main.ENCRYPT_TYPE
     *
     * @mbggenerated
     */
    public void setEncryptType(String encryptType) {
        this.encryptType = encryptType == null ? null : encryptType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CLIENT_IP
     *
     * @return the value of t_order_main.CLIENT_IP
     *
     * @mbggenerated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CLIENT_IP
     *
     * @param clientIp the value for t_order_main.CLIENT_IP
     *
     * @mbggenerated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ACCEPT_SRV_IP
     *
     * @return the value of t_order_main.ACCEPT_SRV_IP
     *
     * @mbggenerated
     */
    public String getAcceptSrvIp() {
        return acceptSrvIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ACCEPT_SRV_IP
     *
     * @param acceptSrvIp the value for t_order_main.ACCEPT_SRV_IP
     *
     * @mbggenerated
     */
    public void setAcceptSrvIp(String acceptSrvIp) {
        this.acceptSrvIp = acceptSrvIp == null ? null : acceptSrvIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.OLD_OUR_TRANS_NO
     *
     * @return the value of t_order_main.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOldOurTransNo() {
        return oldOurTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.OLD_OUR_TRANS_NO
     *
     * @param oldOurTransNo the value for t_order_main.OLD_OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOldOurTransNo(String oldOurTransNo) {
        this.oldOurTransNo = oldOurTransNo == null ? null : oldOurTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.REVERSE_FLAG
     *
     * @return the value of t_order_main.REVERSE_FLAG
     *
     * @mbggenerated
     */
    public String getReverseFlag() {
        return reverseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.REVERSE_FLAG
     *
     * @param reverseFlag the value for t_order_main.REVERSE_FLAG
     *
     * @mbggenerated
     */
    public void setReverseFlag(String reverseFlag) {
        this.reverseFlag = reverseFlag == null ? null : reverseFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.ATTACH
     *
     * @return the value of t_order_main.ATTACH
     *
     * @mbggenerated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.ATTACH
     *
     * @param attach the value for t_order_main.ATTACH
     *
     * @mbggenerated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CHK_STATUS
     *
     * @return the value of t_order_main.CHK_STATUS
     *
     * @mbggenerated
     */
    public String getChkStatus() {
        return chkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CHK_STATUS
     *
     * @param chkStatus the value for t_order_main.CHK_STATUS
     *
     * @mbggenerated
     */
    public void setChkStatus(String chkStatus) {
        this.chkStatus = chkStatus == null ? null : chkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CHK_BATCH_NO
     *
     * @return the value of t_order_main.CHK_BATCH_NO
     *
     * @mbggenerated
     */
    public String getChkBatchNo() {
        return chkBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CHK_BATCH_NO
     *
     * @param chkBatchNo the value for t_order_main.CHK_BATCH_NO
     *
     * @mbggenerated
     */
    public void setChkBatchNo(String chkBatchNo) {
        this.chkBatchNo = chkBatchNo == null ? null : chkBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.DELETE_FLAG
     *
     * @return the value of t_order_main.DELETE_FLAG
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.DELETE_FLAG
     *
     * @param deleteFlag the value for t_order_main.DELETE_FLAG
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.CREATE_TIME
     *
     * @return the value of t_order_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.CREATE_TIME
     *
     * @param createTime the value for t_order_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.LAST_UPD_TIME
     *
     * @return the value of t_order_main.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_order_main.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}