package com.oriental.manage.pojo.transaction;

import java.util.Date;

public class TPayTransDetail extends TPayTransDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.ORDER_NO
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.OUR_TRANS_NO
     *
     * @mbggenerated
     */
    private String ourTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.BANK_CODE
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.BANK_TYPE
     *
     * @mbggenerated
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    private String payOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.ORG_BANK_CODE
     *
     * @mbggenerated
     */
    private String orgBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.TRANS_CODE
     *
     * @mbggenerated
     */
    private String transCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.TRANS_AMT
     *
     * @mbggenerated
     */
    private Long transAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.TRANS_STATUS
     *
     * @mbggenerated
     */
    private String transStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_REQ_NO
     *
     * @mbggenerated
     */
    private String payReqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_REQ_DATE
     *
     * @mbggenerated
     */
    private String payReqDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_RESP_NO
     *
     * @mbggenerated
     */
    private String payRespNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_RESP_DATE
     *
     * @mbggenerated
     */
    private String payRespDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_RESP_CODE
     *
     * @mbggenerated
     */
    private String payRespCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_RESP_DESC
     *
     * @mbggenerated
     */
    private String payRespDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_SETTLE_DATE
     *
     * @mbggenerated
     */
    private Date paySettleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.AUTHORIZATION_CODE
     *
     * @mbggenerated
     */
    private String authorizationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_USER_NAME
     *
     * @mbggenerated
     */
    private String payUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PAY_USER_MOBILE
     *
     * @mbggenerated
     */
    private String payUserMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.BANK_ACC_ID
     *
     * @mbggenerated
     */
    private String bankAccId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.BANK_ACC_PWD
     *
     * @mbggenerated
     */
    private String bankAccPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.BANK_ACC_PHONE
     *
     * @mbggenerated
     */
    private String bankAccPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.HEAD_BANK
     *
     * @mbggenerated
     */
    private String headBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.BRANCH_BANK
     *
     * @mbggenerated
     */
    private String branchBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.SUB_BANK
     *
     * @mbggenerated
     */
    private String subBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.PP_FLAG
     *
     * @mbggenerated
     */
    private String ppFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CD_FLAG
     *
     * @mbggenerated
     */
    private String cdFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.VALID_DATE
     *
     * @mbggenerated
     */
    private String validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CVV2
     *
     * @mbggenerated
     */
    private String cvv2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CERT_TYPE
     *
     * @mbggenerated
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CERT_CODE
     *
     * @mbggenerated
     */
    private String certCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CERT_NAME
     *
     * @mbggenerated
     */
    private String certName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.OLD_PAY_TRANS_NO
     *
     * @mbggenerated
     */
    private String oldPayTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.SETTLE_STATUS
     *
     * @mbggenerated
     */
    private String settleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.SETTLE_BATCH_NO
     *
     * @mbggenerated
     */
    private String settleBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.SETTLE_FLAG
     *
     * @mbggenerated
     */
    private String settleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.REVERSE_FLAG
     *
     * @mbggenerated
     */
    private String reverseFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CHK_STATUS
     *
     * @mbggenerated
     */
    private String chkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.REFUND_FLAG
     *
     * @mbggenerated
     */
    private String refundFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.ACCEPT_SRV_IP
     *
     * @mbggenerated
     */
    private String acceptSrvIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.DIGEST
     *
     * @mbggenerated
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.SYNC_STATUS
     *
     * @mbggenerated
     */
    private String syncStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.DELETE_FLAG
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_trans_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.ORDER_NO
     *
     * @return the value of t_pay_trans_detail.ORDER_NO
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.ORDER_NO
     *
     * @param orderNo the value for t_pay_trans_detail.ORDER_NO
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.ORDER_DATE
     *
     * @return the value of t_pay_trans_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.ORDER_DATE
     *
     * @param orderDate the value for t_pay_trans_detail.ORDER_DATE
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CHANNEL
     *
     * @return the value of t_pay_trans_detail.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CHANNEL
     *
     * @param channel the value for t_pay_trans_detail.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.OUR_TRANS_NO
     *
     * @return the value of t_pay_trans_detail.OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOurTransNo() {
        return ourTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.OUR_TRANS_NO
     *
     * @param ourTransNo the value for t_pay_trans_detail.OUR_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOurTransNo(String ourTransNo) {
        this.ourTransNo = ourTransNo == null ? null : ourTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.BANK_CODE
     *
     * @return the value of t_pay_trans_detail.BANK_CODE
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.BANK_CODE
     *
     * @param bankCode the value for t_pay_trans_detail.BANK_CODE
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.BANK_TYPE
     *
     * @return the value of t_pay_trans_detail.BANK_TYPE
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.BANK_TYPE
     *
     * @param bankType the value for t_pay_trans_detail.BANK_TYPE
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_ORG_CODE
     *
     * @return the value of t_pay_trans_detail.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    public String getPayOrgCode() {
        return payOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_ORG_CODE
     *
     * @param payOrgCode the value for t_pay_trans_detail.PAY_ORG_CODE
     *
     * @mbggenerated
     */
    public void setPayOrgCode(String payOrgCode) {
        this.payOrgCode = payOrgCode == null ? null : payOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.ORG_BANK_CODE
     *
     * @return the value of t_pay_trans_detail.ORG_BANK_CODE
     *
     * @mbggenerated
     */
    public String getOrgBankCode() {
        return orgBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.ORG_BANK_CODE
     *
     * @param orgBankCode the value for t_pay_trans_detail.ORG_BANK_CODE
     *
     * @mbggenerated
     */
    public void setOrgBankCode(String orgBankCode) {
        this.orgBankCode = orgBankCode == null ? null : orgBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.TRANS_CODE
     *
     * @return the value of t_pay_trans_detail.TRANS_CODE
     *
     * @mbggenerated
     */
    public String getTransCode() {
        return transCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.TRANS_CODE
     *
     * @param transCode the value for t_pay_trans_detail.TRANS_CODE
     *
     * @mbggenerated
     */
    public void setTransCode(String transCode) {
        this.transCode = transCode == null ? null : transCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.TRANS_AMT
     *
     * @return the value of t_pay_trans_detail.TRANS_AMT
     *
     * @mbggenerated
     */
    public Long getTransAmt() {
        return transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.TRANS_AMT
     *
     * @param transAmt the value for t_pay_trans_detail.TRANS_AMT
     *
     * @mbggenerated
     */
    public void setTransAmt(Long transAmt) {
        this.transAmt = transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.TRANS_STATUS
     *
     * @return the value of t_pay_trans_detail.TRANS_STATUS
     *
     * @mbggenerated
     */
    public String getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.TRANS_STATUS
     *
     * @param transStatus the value for t_pay_trans_detail.TRANS_STATUS
     *
     * @mbggenerated
     */
    public void setTransStatus(String transStatus) {
        this.transStatus = transStatus == null ? null : transStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_REQ_NO
     *
     * @return the value of t_pay_trans_detail.PAY_REQ_NO
     *
     * @mbggenerated
     */
    public String getPayReqNo() {
        return payReqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_REQ_NO
     *
     * @param payReqNo the value for t_pay_trans_detail.PAY_REQ_NO
     *
     * @mbggenerated
     */
    public void setPayReqNo(String payReqNo) {
        this.payReqNo = payReqNo == null ? null : payReqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_REQ_DATE
     *
     * @return the value of t_pay_trans_detail.PAY_REQ_DATE
     *
     * @mbggenerated
     */
    public String getPayReqDate() {
        return payReqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_REQ_DATE
     *
     * @param payReqDate the value for t_pay_trans_detail.PAY_REQ_DATE
     *
     * @mbggenerated
     */
    public void setPayReqDate(String payReqDate) {
        this.payReqDate = payReqDate == null ? null : payReqDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_RESP_NO
     *
     * @return the value of t_pay_trans_detail.PAY_RESP_NO
     *
     * @mbggenerated
     */
    public String getPayRespNo() {
        return payRespNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_RESP_NO
     *
     * @param payRespNo the value for t_pay_trans_detail.PAY_RESP_NO
     *
     * @mbggenerated
     */
    public void setPayRespNo(String payRespNo) {
        this.payRespNo = payRespNo == null ? null : payRespNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_RESP_DATE
     *
     * @return the value of t_pay_trans_detail.PAY_RESP_DATE
     *
     * @mbggenerated
     */
    public String getPayRespDate() {
        return payRespDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_RESP_DATE
     *
     * @param payRespDate the value for t_pay_trans_detail.PAY_RESP_DATE
     *
     * @mbggenerated
     */
    public void setPayRespDate(String payRespDate) {
        this.payRespDate = payRespDate == null ? null : payRespDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_RESP_CODE
     *
     * @return the value of t_pay_trans_detail.PAY_RESP_CODE
     *
     * @mbggenerated
     */
    public String getPayRespCode() {
        return payRespCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_RESP_CODE
     *
     * @param payRespCode the value for t_pay_trans_detail.PAY_RESP_CODE
     *
     * @mbggenerated
     */
    public void setPayRespCode(String payRespCode) {
        this.payRespCode = payRespCode == null ? null : payRespCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_RESP_DESC
     *
     * @return the value of t_pay_trans_detail.PAY_RESP_DESC
     *
     * @mbggenerated
     */
    public String getPayRespDesc() {
        return payRespDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_RESP_DESC
     *
     * @param payRespDesc the value for t_pay_trans_detail.PAY_RESP_DESC
     *
     * @mbggenerated
     */
    public void setPayRespDesc(String payRespDesc) {
        this.payRespDesc = payRespDesc == null ? null : payRespDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_SETTLE_DATE
     *
     * @return the value of t_pay_trans_detail.PAY_SETTLE_DATE
     *
     * @mbggenerated
     */
    public Date getPaySettleDate() {
        return paySettleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_SETTLE_DATE
     *
     * @param paySettleDate the value for t_pay_trans_detail.PAY_SETTLE_DATE
     *
     * @mbggenerated
     */
    public void setPaySettleDate(Date paySettleDate) {
        this.paySettleDate = paySettleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.AUTHORIZATION_CODE
     *
     * @return the value of t_pay_trans_detail.AUTHORIZATION_CODE
     *
     * @mbggenerated
     */
    public String getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.AUTHORIZATION_CODE
     *
     * @param authorizationCode the value for t_pay_trans_detail.AUTHORIZATION_CODE
     *
     * @mbggenerated
     */
    public void setAuthorizationCode(String authorizationCode) {
        this.authorizationCode = authorizationCode == null ? null : authorizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_USER_NAME
     *
     * @return the value of t_pay_trans_detail.PAY_USER_NAME
     *
     * @mbggenerated
     */
    public String getPayUserName() {
        return payUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_USER_NAME
     *
     * @param payUserName the value for t_pay_trans_detail.PAY_USER_NAME
     *
     * @mbggenerated
     */
    public void setPayUserName(String payUserName) {
        this.payUserName = payUserName == null ? null : payUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PAY_USER_MOBILE
     *
     * @return the value of t_pay_trans_detail.PAY_USER_MOBILE
     *
     * @mbggenerated
     */
    public String getPayUserMobile() {
        return payUserMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PAY_USER_MOBILE
     *
     * @param payUserMobile the value for t_pay_trans_detail.PAY_USER_MOBILE
     *
     * @mbggenerated
     */
    public void setPayUserMobile(String payUserMobile) {
        this.payUserMobile = payUserMobile == null ? null : payUserMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.BANK_ACC_ID
     *
     * @return the value of t_pay_trans_detail.BANK_ACC_ID
     *
     * @mbggenerated
     */
    public String getBankAccId() {
        return bankAccId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.BANK_ACC_ID
     *
     * @param bankAccId the value for t_pay_trans_detail.BANK_ACC_ID
     *
     * @mbggenerated
     */
    public void setBankAccId(String bankAccId) {
        this.bankAccId = bankAccId == null ? null : bankAccId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.BANK_ACC_PWD
     *
     * @return the value of t_pay_trans_detail.BANK_ACC_PWD
     *
     * @mbggenerated
     */
    public String getBankAccPwd() {
        return bankAccPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.BANK_ACC_PWD
     *
     * @param bankAccPwd the value for t_pay_trans_detail.BANK_ACC_PWD
     *
     * @mbggenerated
     */
    public void setBankAccPwd(String bankAccPwd) {
        this.bankAccPwd = bankAccPwd == null ? null : bankAccPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.BANK_ACC_PHONE
     *
     * @return the value of t_pay_trans_detail.BANK_ACC_PHONE
     *
     * @mbggenerated
     */
    public String getBankAccPhone() {
        return bankAccPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.BANK_ACC_PHONE
     *
     * @param bankAccPhone the value for t_pay_trans_detail.BANK_ACC_PHONE
     *
     * @mbggenerated
     */
    public void setBankAccPhone(String bankAccPhone) {
        this.bankAccPhone = bankAccPhone == null ? null : bankAccPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.HEAD_BANK
     *
     * @return the value of t_pay_trans_detail.HEAD_BANK
     *
     * @mbggenerated
     */
    public String getHeadBank() {
        return headBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.HEAD_BANK
     *
     * @param headBank the value for t_pay_trans_detail.HEAD_BANK
     *
     * @mbggenerated
     */
    public void setHeadBank(String headBank) {
        this.headBank = headBank == null ? null : headBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.BRANCH_BANK
     *
     * @return the value of t_pay_trans_detail.BRANCH_BANK
     *
     * @mbggenerated
     */
    public String getBranchBank() {
        return branchBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.BRANCH_BANK
     *
     * @param branchBank the value for t_pay_trans_detail.BRANCH_BANK
     *
     * @mbggenerated
     */
    public void setBranchBank(String branchBank) {
        this.branchBank = branchBank == null ? null : branchBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.SUB_BANK
     *
     * @return the value of t_pay_trans_detail.SUB_BANK
     *
     * @mbggenerated
     */
    public String getSubBank() {
        return subBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.SUB_BANK
     *
     * @param subBank the value for t_pay_trans_detail.SUB_BANK
     *
     * @mbggenerated
     */
    public void setSubBank(String subBank) {
        this.subBank = subBank == null ? null : subBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PROVINCE
     *
     * @return the value of t_pay_trans_detail.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PROVINCE
     *
     * @param province the value for t_pay_trans_detail.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CITY
     *
     * @return the value of t_pay_trans_detail.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CITY
     *
     * @param city the value for t_pay_trans_detail.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.PP_FLAG
     *
     * @return the value of t_pay_trans_detail.PP_FLAG
     *
     * @mbggenerated
     */
    public String getPpFlag() {
        return ppFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.PP_FLAG
     *
     * @param ppFlag the value for t_pay_trans_detail.PP_FLAG
     *
     * @mbggenerated
     */
    public void setPpFlag(String ppFlag) {
        this.ppFlag = ppFlag == null ? null : ppFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CD_FLAG
     *
     * @return the value of t_pay_trans_detail.CD_FLAG
     *
     * @mbggenerated
     */
    public String getCdFlag() {
        return cdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CD_FLAG
     *
     * @param cdFlag the value for t_pay_trans_detail.CD_FLAG
     *
     * @mbggenerated
     */
    public void setCdFlag(String cdFlag) {
        this.cdFlag = cdFlag == null ? null : cdFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.VALID_DATE
     *
     * @return the value of t_pay_trans_detail.VALID_DATE
     *
     * @mbggenerated
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.VALID_DATE
     *
     * @param validDate the value for t_pay_trans_detail.VALID_DATE
     *
     * @mbggenerated
     */
    public void setValidDate(String validDate) {
        this.validDate = validDate == null ? null : validDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CVV2
     *
     * @return the value of t_pay_trans_detail.CVV2
     *
     * @mbggenerated
     */
    public String getCvv2() {
        return cvv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CVV2
     *
     * @param cvv2 the value for t_pay_trans_detail.CVV2
     *
     * @mbggenerated
     */
    public void setCvv2(String cvv2) {
        this.cvv2 = cvv2 == null ? null : cvv2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CERT_TYPE
     *
     * @return the value of t_pay_trans_detail.CERT_TYPE
     *
     * @mbggenerated
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CERT_TYPE
     *
     * @param certType the value for t_pay_trans_detail.CERT_TYPE
     *
     * @mbggenerated
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CERT_CODE
     *
     * @return the value of t_pay_trans_detail.CERT_CODE
     *
     * @mbggenerated
     */
    public String getCertCode() {
        return certCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CERT_CODE
     *
     * @param certCode the value for t_pay_trans_detail.CERT_CODE
     *
     * @mbggenerated
     */
    public void setCertCode(String certCode) {
        this.certCode = certCode == null ? null : certCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CERT_NAME
     *
     * @return the value of t_pay_trans_detail.CERT_NAME
     *
     * @mbggenerated
     */
    public String getCertName() {
        return certName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CERT_NAME
     *
     * @param certName the value for t_pay_trans_detail.CERT_NAME
     *
     * @mbggenerated
     */
    public void setCertName(String certName) {
        this.certName = certName == null ? null : certName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.OLD_PAY_TRANS_NO
     *
     * @return the value of t_pay_trans_detail.OLD_PAY_TRANS_NO
     *
     * @mbggenerated
     */
    public String getOldPayTransNo() {
        return oldPayTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.OLD_PAY_TRANS_NO
     *
     * @param oldPayTransNo the value for t_pay_trans_detail.OLD_PAY_TRANS_NO
     *
     * @mbggenerated
     */
    public void setOldPayTransNo(String oldPayTransNo) {
        this.oldPayTransNo = oldPayTransNo == null ? null : oldPayTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.SETTLE_STATUS
     *
     * @return the value of t_pay_trans_detail.SETTLE_STATUS
     *
     * @mbggenerated
     */
    public String getSettleStatus() {
        return settleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.SETTLE_STATUS
     *
     * @param settleStatus the value for t_pay_trans_detail.SETTLE_STATUS
     *
     * @mbggenerated
     */
    public void setSettleStatus(String settleStatus) {
        this.settleStatus = settleStatus == null ? null : settleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.SETTLE_BATCH_NO
     *
     * @return the value of t_pay_trans_detail.SETTLE_BATCH_NO
     *
     * @mbggenerated
     */
    public String getSettleBatchNo() {
        return settleBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.SETTLE_BATCH_NO
     *
     * @param settleBatchNo the value for t_pay_trans_detail.SETTLE_BATCH_NO
     *
     * @mbggenerated
     */
    public void setSettleBatchNo(String settleBatchNo) {
        this.settleBatchNo = settleBatchNo == null ? null : settleBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.SETTLE_FLAG
     *
     * @return the value of t_pay_trans_detail.SETTLE_FLAG
     *
     * @mbggenerated
     */
    public String getSettleFlag() {
        return settleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.SETTLE_FLAG
     *
     * @param settleFlag the value for t_pay_trans_detail.SETTLE_FLAG
     *
     * @mbggenerated
     */
    public void setSettleFlag(String settleFlag) {
        this.settleFlag = settleFlag == null ? null : settleFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.REVERSE_FLAG
     *
     * @return the value of t_pay_trans_detail.REVERSE_FLAG
     *
     * @mbggenerated
     */
    public String getReverseFlag() {
        return reverseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.REVERSE_FLAG
     *
     * @param reverseFlag the value for t_pay_trans_detail.REVERSE_FLAG
     *
     * @mbggenerated
     */
    public void setReverseFlag(String reverseFlag) {
        this.reverseFlag = reverseFlag == null ? null : reverseFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CHK_STATUS
     *
     * @return the value of t_pay_trans_detail.CHK_STATUS
     *
     * @mbggenerated
     */
    public String getChkStatus() {
        return chkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CHK_STATUS
     *
     * @param chkStatus the value for t_pay_trans_detail.CHK_STATUS
     *
     * @mbggenerated
     */
    public void setChkStatus(String chkStatus) {
        this.chkStatus = chkStatus == null ? null : chkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.REFUND_FLAG
     *
     * @return the value of t_pay_trans_detail.REFUND_FLAG
     *
     * @mbggenerated
     */
    public String getRefundFlag() {
        return refundFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.REFUND_FLAG
     *
     * @param refundFlag the value for t_pay_trans_detail.REFUND_FLAG
     *
     * @mbggenerated
     */
    public void setRefundFlag(String refundFlag) {
        this.refundFlag = refundFlag == null ? null : refundFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.ACCEPT_SRV_IP
     *
     * @return the value of t_pay_trans_detail.ACCEPT_SRV_IP
     *
     * @mbggenerated
     */
    public String getAcceptSrvIp() {
        return acceptSrvIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.ACCEPT_SRV_IP
     *
     * @param acceptSrvIp the value for t_pay_trans_detail.ACCEPT_SRV_IP
     *
     * @mbggenerated
     */
    public void setAcceptSrvIp(String acceptSrvIp) {
        this.acceptSrvIp = acceptSrvIp == null ? null : acceptSrvIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.DIGEST
     *
     * @return the value of t_pay_trans_detail.DIGEST
     *
     * @mbggenerated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.DIGEST
     *
     * @param digest the value for t_pay_trans_detail.DIGEST
     *
     * @mbggenerated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.SYNC_STATUS
     *
     * @return the value of t_pay_trans_detail.SYNC_STATUS
     *
     * @mbggenerated
     */
    public String getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.SYNC_STATUS
     *
     * @param syncStatus the value for t_pay_trans_detail.SYNC_STATUS
     *
     * @mbggenerated
     */
    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus == null ? null : syncStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.DELETE_FLAG
     *
     * @return the value of t_pay_trans_detail.DELETE_FLAG
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.DELETE_FLAG
     *
     * @param deleteFlag the value for t_pay_trans_detail.DELETE_FLAG
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.CREATE_TIME
     *
     * @return the value of t_pay_trans_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.CREATE_TIME
     *
     * @param createTime the value for t_pay_trans_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_trans_detail.LAST_UPD_TIME
     *
     * @return the value of t_pay_trans_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_trans_detail.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_pay_trans_detail.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}