package com.oriental.manage.pojo.base;

import java.util.Date;

public class AuthCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_cfg.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_cfg.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_cfg.RSRC_CODE
     *
     * @mbggenerated
     */
    private String rsrcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_cfg.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_cfg.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_cfg.ID
     *
     * @return the value of t_auth_cfg.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_cfg.ID
     *
     * @param id the value for t_auth_cfg.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_cfg.ROLE_ID
     *
     * @return the value of t_auth_cfg.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_cfg.ROLE_ID
     *
     * @param roleId the value for t_auth_cfg.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_cfg.RSRC_CODE
     *
     * @return the value of t_auth_cfg.RSRC_CODE
     *
     * @mbggenerated
     */
    public String getRsrcCode() {
        return rsrcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_cfg.RSRC_CODE
     *
     * @param rsrcCode the value for t_auth_cfg.RSRC_CODE
     *
     * @mbggenerated
     */
    public void setRsrcCode(String rsrcCode) {
        this.rsrcCode = rsrcCode == null ? null : rsrcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_cfg.CREATE_TIME
     *
     * @return the value of t_auth_cfg.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_cfg.CREATE_TIME
     *
     * @param createTime the value for t_auth_cfg.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_cfg.LAST_UPD_TIME
     *
     * @return the value of t_auth_cfg.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_cfg.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_auth_cfg.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }
}