package com.oriental.manage.pojo.base;

import lombok.ToString;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.List;

@ToString(callSuper = true)
public class DataDict extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ITEM_NAME
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.COL_NAME_CN
     *
     * @mbggenerated
     */
    private String colNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.COL_NAME
     *
     * @mbggenerated
     */
    private String colName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ITEM_VAL
     *
     * @mbggenerated
     */
    private String itemVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ITEM_DESC
     *
     * @mbggenerated
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.SPARE1
     *
     * @mbggenerated
     */
    private String spare1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.CREATE_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyyMMdd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyyMMdd")
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_dict.ITEM_TYPE
     *
     * @mbggenerated
     */
    private String itemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ID
     *
     * @return the value of t_data_dict.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ID
     *
     * @param id the value for t_data_dict.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ITEM_NAME
     *
     * @return the value of t_data_dict.ITEM_NAME
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ITEM_NAME
     *
     * @param itemName the value for t_data_dict.ITEM_NAME
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.COL_NAME_CN
     *
     * @return the value of t_data_dict.COL_NAME_CN
     *
     * @mbggenerated
     */
    public String getColNameCn() {
        return colNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.COL_NAME_CN
     *
     * @param colNameCn the value for t_data_dict.COL_NAME_CN
     *
     * @mbggenerated
     */
    public void setColNameCn(String colNameCn) {
        this.colNameCn = colNameCn == null ? null : colNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.COL_NAME
     *
     * @return the value of t_data_dict.COL_NAME
     *
     * @mbggenerated
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.COL_NAME
     *
     * @param colName the value for t_data_dict.COL_NAME
     *
     * @mbggenerated
     */
    public void setColName(String colName) {
        this.colName = colName == null ? null : colName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ITEM_VAL
     *
     * @return the value of t_data_dict.ITEM_VAL
     *
     * @mbggenerated
     */
    public String getItemVal() {
        return itemVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ITEM_VAL
     *
     * @param itemVal the value for t_data_dict.ITEM_VAL
     *
     * @mbggenerated
     */
    public void setItemVal(String itemVal) {
        this.itemVal = itemVal == null ? null : itemVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ITEM_DESC
     *
     * @return the value of t_data_dict.ITEM_DESC
     *
     * @mbggenerated
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ITEM_DESC
     *
     * @param itemDesc the value for t_data_dict.ITEM_DESC
     *
     * @mbggenerated
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc == null ? null : itemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.SPARE1
     *
     * @return the value of t_data_dict.SPARE1
     *
     * @mbggenerated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.SPARE1
     *
     * @param spare1 the value for t_data_dict.SPARE1
     *
     * @mbggenerated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.CREATE_TIME
     *
     * @return the value of t_data_dict.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.CREATE_TIME
     *
     * @param createTime the value for t_data_dict.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.LAST_UPD_TIME
     *
     * @return the value of t_data_dict.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_data_dict.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_dict.ITEM_TYPE
     *
     * @return the value of t_data_dict.ITEM_TYPE
     *
     * @mbggenerated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_dict.ITEM_TYPE
     *
     * @param itemType the value for t_data_dict.ITEM_TYPE
     *
     * @mbggenerated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }


    //数据字典列值项集合
    private List<String> itemValList;
    public List<String> getItemValList() {
        return itemValList;
    }

    public void setItemValList(List<String> itemValList) {
        this.itemValList = itemValList;
    }

}