package com.oriental.manage.pojo.base;

import java.util.Date;

public class DfsFileInfo extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.BUSI_TYPE
     *
     * @mbggenerated
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.COMPANY_TYPE
     *
     * @mbggenerated
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.COMPANY_CODE
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.LOCAL_FILENAME
     *
     * @mbggenerated
     */
    private String localFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.DFS_FULL_FILENAME
     *
     * @mbggenerated
     */
    private String dfsFullFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.DFS_GROUPNAME
     *
     * @mbggenerated
     */
    private String dfsGroupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.BANK_SETTLE_DATE
     *
     * @mbggenerated
     */
    private Date bankSettleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.DOCUMENT_TYPE
     *
     * @mbggenerated
     */
    private String documentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.DOCUMENT_TITLE
     *
     * @mbggenerated
     */
    private String documentTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.CONN_CHANNEL
     *
     * @mbggenerated
     */
    private String connChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dfs_file_info.DOCUMENT_VERSION
     *
     * @mbggenerated
     */
    private String documentVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.ID
     *
     * @return the value of t_dfs_file_info.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.ID
     *
     * @param id the value for t_dfs_file_info.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.BUSI_TYPE
     *
     * @return the value of t_dfs_file_info.BUSI_TYPE
     *
     * @mbggenerated
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.BUSI_TYPE
     *
     * @param busiType the value for t_dfs_file_info.BUSI_TYPE
     *
     * @mbggenerated
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.COMPANY_TYPE
     *
     * @return the value of t_dfs_file_info.COMPANY_TYPE
     *
     * @mbggenerated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.COMPANY_TYPE
     *
     * @param companyType the value for t_dfs_file_info.COMPANY_TYPE
     *
     * @mbggenerated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.COMPANY_CODE
     *
     * @return the value of t_dfs_file_info.COMPANY_CODE
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.COMPANY_CODE
     *
     * @param companyCode the value for t_dfs_file_info.COMPANY_CODE
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.LOCAL_FILENAME
     *
     * @return the value of t_dfs_file_info.LOCAL_FILENAME
     *
     * @mbggenerated
     */
    public String getLocalFilename() {
        return localFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.LOCAL_FILENAME
     *
     * @param localFilename the value for t_dfs_file_info.LOCAL_FILENAME
     *
     * @mbggenerated
     */
    public void setLocalFilename(String localFilename) {
        this.localFilename = localFilename == null ? null : localFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.DFS_FULL_FILENAME
     *
     * @return the value of t_dfs_file_info.DFS_FULL_FILENAME
     *
     * @mbggenerated
     */
    public String getDfsFullFilename() {
        return dfsFullFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.DFS_FULL_FILENAME
     *
     * @param dfsFullFilename the value for t_dfs_file_info.DFS_FULL_FILENAME
     *
     * @mbggenerated
     */
    public void setDfsFullFilename(String dfsFullFilename) {
        this.dfsFullFilename = dfsFullFilename == null ? null : dfsFullFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.REMARK
     *
     * @return the value of t_dfs_file_info.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.REMARK
     *
     * @param remark the value for t_dfs_file_info.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.CREATE_TIME
     *
     * @return the value of t_dfs_file_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.CREATE_TIME
     *
     * @param createTime the value for t_dfs_file_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.LAST_UPD_TIME
     *
     * @return the value of t_dfs_file_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_dfs_file_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.DFS_GROUPNAME
     *
     * @return the value of t_dfs_file_info.DFS_GROUPNAME
     *
     * @mbggenerated
     */
    public String getDfsGroupname() {
        return dfsGroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.DFS_GROUPNAME
     *
     * @param dfsGroupname the value for t_dfs_file_info.DFS_GROUPNAME
     *
     * @mbggenerated
     */
    public void setDfsGroupname(String dfsGroupname) {
        this.dfsGroupname = dfsGroupname == null ? null : dfsGroupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.STATUS
     *
     * @return the value of t_dfs_file_info.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.STATUS
     *
     * @param status the value for t_dfs_file_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.OPERATOR
     *
     * @return the value of t_dfs_file_info.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.OPERATOR
     *
     * @param operator the value for t_dfs_file_info.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.BANK_SETTLE_DATE
     *
     * @return the value of t_dfs_file_info.BANK_SETTLE_DATE
     *
     * @mbggenerated
     */
    public Date getBankSettleDate() {
        return bankSettleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.BANK_SETTLE_DATE
     *
     * @param bankSettleDate the value for t_dfs_file_info.BANK_SETTLE_DATE
     *
     * @mbggenerated
     */
    public void setBankSettleDate(Date bankSettleDate) {
        this.bankSettleDate = bankSettleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.DOCUMENT_TYPE
     *
     * @return the value of t_dfs_file_info.DOCUMENT_TYPE
     *
     * @mbggenerated
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.DOCUMENT_TYPE
     *
     * @param documentType the value for t_dfs_file_info.DOCUMENT_TYPE
     *
     * @mbggenerated
     */
    public void setDocumentType(String documentType) {
        this.documentType = documentType == null ? null : documentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.DOCUMENT_TITLE
     *
     * @return the value of t_dfs_file_info.DOCUMENT_TITLE
     *
     * @mbggenerated
     */
    public String getDocumentTitle() {
        return documentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.DOCUMENT_TITLE
     *
     * @param documentTitle the value for t_dfs_file_info.DOCUMENT_TITLE
     *
     * @mbggenerated
     */
    public void setDocumentTitle(String documentTitle) {
        this.documentTitle = documentTitle == null ? null : documentTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.CONN_CHANNEL
     *
     * @return the value of t_dfs_file_info.CONN_CHANNEL
     *
     * @mbggenerated
     */
    public String getConnChannel() {
        return connChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.CONN_CHANNEL
     *
     * @param connChannel the value for t_dfs_file_info.CONN_CHANNEL
     *
     * @mbggenerated
     */
    public void setConnChannel(String connChannel) {
        this.connChannel = connChannel == null ? null : connChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dfs_file_info.DOCUMENT_VERSION
     *
     * @return the value of t_dfs_file_info.DOCUMENT_VERSION
     *
     * @mbggenerated
     */
    public String getDocumentVersion() {
        return documentVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dfs_file_info.DOCUMENT_VERSION
     *
     * @param documentVersion the value for t_dfs_file_info.DOCUMENT_VERSION
     *
     * @mbggenerated
     */
    public void setDocumentVersion(String documentVersion) {
        this.documentVersion = documentVersion == null ? null : documentVersion.trim();
    }
}