package com.oriental.manage.pojo.base;

import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@ToString
public class ResourceInfo implements Serializable{

    private static final long serialVersionUID = -3021583855478834240L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_NAME
     *
     * @mbggenerated
     */
    private String rsrcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_DESC
     *
     * @mbggenerated
     */
    private String rsrcDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.PARENT_RSRC_CODE
     *
     * @mbggenerated
     */
    private String parentRsrcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_URL
     *
     * @mbggenerated
     */
    private String rsrcUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_TYPE
     *
     * @mbggenerated
     */
    private String rsrcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_OPERATION
     *
     * @mbggenerated
     */
    private String rsrcOperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_VISABLE_FLAG
     *
     * @mbggenerated
     */
    private String rsrcVisableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_DSP_ORDER
     *
     * @mbggenerated
     */
    private String rsrcDspOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_STATUS
     *
     * @mbggenerated
     */
    private String rsrcStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.SPARE1
     *
     * @mbggenerated
     */
    private String spare1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RESOURCE_TYPE
     *
     * @mbggenerated
     */
    private String resourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_CODE
     *
     * @return the value of t_resource_info.RSRC_CODE
     *
     * @mbggenerated
     */
    public String getRsrcCode() {
        return rsrcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_CODE
     *
     * @param rsrcCode the value for t_resource_info.RSRC_CODE
     *
     * @mbggenerated
     */
    public void setRsrcCode(String rsrcCode) {
        this.rsrcCode = rsrcCode == null ? null : rsrcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_NAME
     *
     * @return the value of t_resource_info.RSRC_NAME
     *
     * @mbggenerated
     */
    public String getRsrcName() {
        return rsrcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_NAME
     *
     * @param rsrcName the value for t_resource_info.RSRC_NAME
     *
     * @mbggenerated
     */
    public void setRsrcName(String rsrcName) {
        this.rsrcName = rsrcName == null ? null : rsrcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_DESC
     *
     * @return the value of t_resource_info.RSRC_DESC
     *
     * @mbggenerated
     */
    public String getRsrcDesc() {
        return rsrcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_DESC
     *
     * @param rsrcDesc the value for t_resource_info.RSRC_DESC
     *
     * @mbggenerated
     */
    public void setRsrcDesc(String rsrcDesc) {
        this.rsrcDesc = rsrcDesc == null ? null : rsrcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.PARENT_RSRC_CODE
     *
     * @return the value of t_resource_info.PARENT_RSRC_CODE
     *
     * @mbggenerated
     */
    public String getParentRsrcCode() {
        return parentRsrcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.PARENT_RSRC_CODE
     *
     * @param parentRsrcCode the value for t_resource_info.PARENT_RSRC_CODE
     *
     * @mbggenerated
     */
    public void setParentRsrcCode(String parentRsrcCode) {
        this.parentRsrcCode = parentRsrcCode == null ? null : parentRsrcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_URL
     *
     * @return the value of t_resource_info.RSRC_URL
     *
     * @mbggenerated
     */
    public String getRsrcUrl() {
        return rsrcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_URL
     *
     * @param rsrcUrl the value for t_resource_info.RSRC_URL
     *
     * @mbggenerated
     */
    public void setRsrcUrl(String rsrcUrl) {
        this.rsrcUrl = rsrcUrl == null ? null : rsrcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_TYPE
     *
     * @return the value of t_resource_info.RSRC_TYPE
     *
     * @mbggenerated
     */
    public String getRsrcType() {
        return rsrcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_TYPE
     *
     * @param rsrcType the value for t_resource_info.RSRC_TYPE
     *
     * @mbggenerated
     */
    public void setRsrcType(String rsrcType) {
        this.rsrcType = rsrcType == null ? null : rsrcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_OPERATION
     *
     * @return the value of t_resource_info.RSRC_OPERATION
     *
     * @mbggenerated
     */
    public String getRsrcOperation() {
        return rsrcOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_OPERATION
     *
     * @param rsrcOperation the value for t_resource_info.RSRC_OPERATION
     *
     * @mbggenerated
     */
    public void setRsrcOperation(String rsrcOperation) {
        this.rsrcOperation = rsrcOperation == null ? null : rsrcOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_VISABLE_FLAG
     *
     * @return the value of t_resource_info.RSRC_VISABLE_FLAG
     *
     * @mbggenerated
     */
    public String getRsrcVisableFlag() {
        return rsrcVisableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_VISABLE_FLAG
     *
     * @param rsrcVisableFlag the value for t_resource_info.RSRC_VISABLE_FLAG
     *
     * @mbggenerated
     */
    public void setRsrcVisableFlag(String rsrcVisableFlag) {
        this.rsrcVisableFlag = rsrcVisableFlag == null ? null : rsrcVisableFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_DSP_ORDER
     *
     * @return the value of t_resource_info.RSRC_DSP_ORDER
     *
     * @mbggenerated
     */
    public String getRsrcDspOrder() {
        return rsrcDspOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_DSP_ORDER
     *
     * @param rsrcDspOrder the value for t_resource_info.RSRC_DSP_ORDER
     *
     * @mbggenerated
     */
    public void setRsrcDspOrder(String rsrcDspOrder) {
        this.rsrcDspOrder = rsrcDspOrder == null ? null : rsrcDspOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RSRC_STATUS
     *
     * @return the value of t_resource_info.RSRC_STATUS
     *
     * @mbggenerated
     */
    public String getRsrcStatus() {
        return rsrcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RSRC_STATUS
     *
     * @param rsrcStatus the value for t_resource_info.RSRC_STATUS
     *
     * @mbggenerated
     */
    public void setRsrcStatus(String rsrcStatus) {
        this.rsrcStatus = rsrcStatus == null ? null : rsrcStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.SPARE1
     *
     * @return the value of t_resource_info.SPARE1
     *
     * @mbggenerated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.SPARE1
     *
     * @param spare1 the value for t_resource_info.SPARE1
     *
     * @mbggenerated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.CREATE_TIME
     *
     * @return the value of t_resource_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.CREATE_TIME
     *
     * @param createTime the value for t_resource_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.LAST_UPD_TIME
     *
     * @return the value of t_resource_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_resource_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource_info.RESOURCE_TYPE
     *
     * @return the value of t_resource_info.RESOURCE_TYPE
     *
     * @mbggenerated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource_info.RESOURCE_TYPE
     *
     * @param resourceType the value for t_resource_info.RESOURCE_TYPE
     *
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    @Override
    public int hashCode() {
        return this.rsrcCode.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource_info.RSRC_CODE
     *
     * @mbggenerated
     */
    private String rsrcCode;
}