package com.oriental.manage.pojo.base;

import java.util.Date;

public class RoleInfo extends BaseModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.ROLE_DESC
     *
     * @mbggenerated
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.PWD_VALID_CYC
     *
     * @mbggenerated
     */
    private String pwdValidCyc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.READONLY_FLAG
     *
     * @mbggenerated
     */
    private String readonlyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.SPARE1
     *
     * @mbggenerated
     */
    private String spare1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.MODIFIER
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_info.ROLE_TYPE
     *
     * @mbggenerated
     */
    private String roleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.ROLE_ID
     *
     * @return the value of t_role_info.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.ROLE_ID
     *
     * @param roleId the value for t_role_info.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.ROLE_NAME
     *
     * @return the value of t_role_info.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.ROLE_NAME
     *
     * @param roleName the value for t_role_info.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.ROLE_DESC
     *
     * @return the value of t_role_info.ROLE_DESC
     *
     * @mbggenerated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.ROLE_DESC
     *
     * @param roleDesc the value for t_role_info.ROLE_DESC
     *
     * @mbggenerated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.AREA_CODE
     *
     * @return the value of t_role_info.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.AREA_CODE
     *
     * @param areaCode the value for t_role_info.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.PWD_VALID_CYC
     *
     * @return the value of t_role_info.PWD_VALID_CYC
     *
     * @mbggenerated
     */
    public String getPwdValidCyc() {
        return pwdValidCyc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.PWD_VALID_CYC
     *
     * @param pwdValidCyc the value for t_role_info.PWD_VALID_CYC
     *
     * @mbggenerated
     */
    public void setPwdValidCyc(String pwdValidCyc) {
        this.pwdValidCyc = pwdValidCyc == null ? null : pwdValidCyc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.READONLY_FLAG
     *
     * @return the value of t_role_info.READONLY_FLAG
     *
     * @mbggenerated
     */
    public String getReadonlyFlag() {
        return readonlyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.READONLY_FLAG
     *
     * @param readonlyFlag the value for t_role_info.READONLY_FLAG
     *
     * @mbggenerated
     */
    public void setReadonlyFlag(String readonlyFlag) {
        this.readonlyFlag = readonlyFlag == null ? null : readonlyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.SPARE1
     *
     * @return the value of t_role_info.SPARE1
     *
     * @mbggenerated
     */
    public String getSpare1() {
        return spare1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.SPARE1
     *
     * @param spare1 the value for t_role_info.SPARE1
     *
     * @mbggenerated
     */
    public void setSpare1(String spare1) {
        this.spare1 = spare1 == null ? null : spare1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.CREATE_TIME
     *
     * @return the value of t_role_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.CREATE_TIME
     *
     * @param createTime the value for t_role_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.LAST_UPD_TIME
     *
     * @return the value of t_role_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for t_role_info.LAST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.CREATOR
     *
     * @return the value of t_role_info.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.CREATOR
     *
     * @param creator the value for t_role_info.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.MODIFIER
     *
     * @return the value of t_role_info.MODIFIER
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.MODIFIER
     *
     * @param modifier the value for t_role_info.MODIFIER
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_info.ROLE_TYPE
     *
     * @return the value of t_role_info.ROLE_TYPE
     *
     * @mbggenerated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_info.ROLE_TYPE
     *
     * @param roleType the value for t_role_info.ROLE_TYPE
     *
     * @mbggenerated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }
}